<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginatedPerUser(User $user, $page, $resultsPerPage)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT comment
                FROM AppBundle:Comment comment
                WHERE comment.user = :userId
                ORDER BY comment.createdAt DESC
            ')
            ->setParameter('userId', $user->getId())
            ->setFirstResult($resultsPerPage * ($page - 1))
            ->setMaxResults($resultsPerPage)
            ->getResult();
    }

    public function countPerUser(User $user)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT COUNT(comment)
                FROM AppBundle:Comment comment
                WHERE comment.user = :userId
            ')
            ->setParameter('userId', $user->getId())
            ->getSingleScalarResult();
    }
}
